- hosts: localhost
  vars:
    ansible_user: $USERNAME
    packages:
      - build-essential
      - bash
      - fish
      - curl
      - docker
      - docker-compose

  become: true

  tasks:

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: Set fish as default shell
      shell: chsh -s /usr/bin/fish {{ ansible_user }}

    - name: Copy fish aliases
      copy:
        src: aliases/.
        dest: $HOME/.config/fish/functions/
