window-decoration = true

background-opacity = 0.75

keybind = super+n=new_tab
keybind = super+shift+left=previous_tab
keybind = super+shift+right=next_tab
keybind = super+w=close_window

keybind = super+d=new_split:down
keybind = super+shift+d=new_split:right
keybind = super+alt+h=goto_split:left
keybind = super+alt+l=goto_split:right
keybind = super+alt+k=goto_split:top
keybind = super+alt+j=goto_split:bottom
keybind = super+alt+x=close_surface

keybind = super+ctrl+right=resize_split:right,10
keybind = super+ctrl+left=resize_split:left,10
keybind = super+ctrl+down=resize_split:down,10
keybind = super+ctrl+up=resize_split:up,10

keybind = ctrl+shift+j=scroll_page_down
keybind = ctrl+shift+k=scroll_page_up

keybind = super+shift+d=toggle_window_decorations
keybind = super+shift+x=toggle_tab_overview
