"$schema" = 'https://starship.rs/config-schema.json'

format = "$directory$git_branch$git_status${env_var.VENV_NAME}$character"

[directory]
format = "[$path](blue)"
truncation_length = 1
truncation_symbol = ""

[git_branch]
format = " [$branch](magenta)"
symbol = ""

[git_status]
format = "[$all_status$ahead_behind](red)"
modified = "*"
staged = "+"
untracked = "?"
ahead = "⇡"
behind = "⇣"
deleted = ""

[env_var.VENV_NAME]
format = " [$env_value](cyan)"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
